### ISSUE TITLE
Module not found!

### ISSUE THREAD

**Issue by mohit-kumar-singh55** [mohit-kumar-singh55/react-timepicker-clock#1]
Hi,

This is my first npm package that I have published but even after many tries, I am not able to use/test it because after successful installation using
`npm install react-timepicker-clock`
when i try to import it `import TimePickerClock from 'react-timepicker-clock';` , it says `Module not found`

I am unable to find why module is not found.

**Comment by DamyanBG** [comment]
Hello, 

I will try to help you.

**Comment by DamyanBG** [comment]
`
 "main": "pages/index.js",
"type": "module",
  "exports": {
    ".": "./pages/index.js",
    "./*": "./pages/*.js"
  },
  "files": [
    "pages/*"
  ],
`

**Comment by DamyanBG** [comment]
You can add this to your package.json. With that you will tell that the main folder is pages. I can see that there is another error after fixing the module, but for now this is from me.

**Comment by mohit-kumar-singh55** [comment]
Thank you, I will try it & will share the result.

**Comment by mohit-kumar-singh55** [comment]
@DamyanBG Thank you for helping, this issue is fixed now but another error occured, please take a look at #2 if you can also help with this.
